import 'package:edukaquiz_app/home.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Badmintoon extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: double.infinity,
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Column(
            children: <Widget>[
              SizedBox(height: 70,),
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child:
                Image.asset('assets/gambarbulutangkis.png' , width: 350.0,),
              ),
              SizedBox(height: 40,),
              SingleChildScrollView(
                child: Container(
                  width: 450,
                  decoration: BoxDecoration(
                    color: Color(0xff59E0FE),
                    borderRadius: BorderRadius.only(topLeft: Radius.circular(60), topRight: Radius.circular(60),
                    ),
                  ),
                  child: Container(
                    margin: EdgeInsets.all(25),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        SizedBox(height: 10,),
                        Align(
                          alignment: Alignment.centerLeft,
                          child: Text(
                            'Bulu Tangkis',
                            style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                          ),
                        ),
                        SizedBox(height: 8,),
                        Text('Pengertian Bulu Tangkis',style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),textAlign: TextAlign.justify, ),
                        SizedBox(height: 8,),
                        Text(
                          'Permainan ini terdiri dari dua kata, yaitu bulu dan tangkis. Secara harfiah, olahraga ini bisa diartikan sebagai permainan yang dilakukan dengan cara menangkis bola bulu menggunakan raket. Bolanya sendiri merujuk pada kok yang memang terbuat dari bulu-bulu hewan unggas.', textAlign: TextAlign.justify,),
                        Text(
                          'Bulu tangkis harus dimainkan oleh sedikitnya dua orang. Tujuan dari permainan ini adalah memukul kok hingga bisa melayang melewati net, kemudian jatuh ke lantai di area lawan agar terhitung sebagai poin.',
                          style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Bulu tangkis memang terlihat mudah dilakukan, tetapi olahraga ini butuh latihan dan kerja keras tinggi untuk benar-benar bisa menguasainya. Belum lagi ada sederet peraturan yang harus Anda pahami apabila berniat menekuni olahraga yang satu ini.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 10,),
                        Text('Peraturan Bulu Tangkis', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Permainan bulu tangkis memiliki sejumlah peraturan yang harus dipatuhi oleh semua pemain. Peraturan tersebut meliputi jumlah pemain, cara memulai pertandingan, hingga sistem penghitungan skor.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('1. Perlengkapan Bulu Tangkis', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Raket -> raket memiliki panjang maksimal 68 cm dan lebar 22 cm. Panjang kepala raket atau area senar adalah 28 cm dengan lebar 22 cm. Raket bisa terbuat dari kayu atau aluminium dengan berat tak lebih dari 150 gram.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Kok -> kokterbuat dari enam belas helai bulu yang ditancapkan pada gabus berdiameter 25–28 mm. Berat standar kok adalah sekitar 4,74–5,5 gram, sedangkan tinggi kok antara 64–74 mm.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('2. Jumlah Pemain', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Tunggal, yaitu satu lawan satu dan bisa dimainkan oleh putra maupun putri.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Ganda, yaitu satu tim terdiri dari dua orang.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Ganda campuran, yaitu satu tim terdiri dari 2 orang, 1 putra dan 1 putri.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('3. Penentuan Awal Permainan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Pertandingan diawali dengan undian, yaitu menggunakan metode lempar koin yang dilakukan oleh wasit. Undian ini untuk menentukan pemain mana yang harus melakukan servis terlebih dahulu.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('4. Penghitungan Skor', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Penentuan kemenangan di olahraga ini menggunakan sistem best of three (pemenang dua babak). Jadi, permainan bulu tangkis bisa berlangsung sebanyak 2–3 babak. Apabila ada pemain yang memenangkan dua set berturut-turut, babak ketiga tidak perlu dilakukan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Di tiap setnya, pemenang adalah pemain yang berhasil mengumpulkan poin 21 lebih dulu. Apabila terjadi kedudukan imbang di skor 20-20 (yus), pertandingan akan dilanjutkan sampai salah satu tim unggul dengan selisih dua poin.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('5. Pelanggaran:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Kok menyangkut di net.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Raket menyentuh net saat memukul kok.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Saat melakukan pukulan, raket melewati net dan masuk ke area tim lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Kok sudah dipukul tetapi jatuh di area sendiri (tidak berhasil melewati net).', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Saat menerima servis, pemain sudah bergerak dulu sebelum kok berhasil dipukul.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Saat melakukan/menerima servis, pemain menginjak garis batas lapangan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Kok jatuh di luar lapangan atau meluncur lewat bawah net.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Kok dipukul dua kali, baik oleh satu maupun dua pemain dalam satu tim.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Pemain sengaja mengulur-ulur waktu pertandingan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Pemain secara sengaja melakukan hal yang mengganggu tim lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Ukuran Lapangan Bulu Tangkis', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Image.asset('assets/ukuranlapanganbad.jpg' , width: 350.0,),
                        SizedBox(height: 8,),
                        Text('Ukuran Lapangan Standar PBSI:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Panjang : 13,40 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Lebar : 6,10 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Tinggi tiang net : 1,55 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Tinggi net : 1,52 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Jarak garis servis depan ke net : 1,98 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Jarak garis servis tengah ke garis samping : 3,05 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Jarak garis servis belakang ke garis belakang : 0,76 meter (permainan ganda)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Jarak garis samping ke pinggir lapangan : 0,46 meter (permainan tunggal)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Ukuran Lapangan Standar BWF:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Panjang : 13,4 meter (tunggal dan ganda)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('- Lebar : 5,18 meter (tunggal) dan 6,1 meter (ganda)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Bulu Tangkis', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Sama halnya dengan olahraga lainnya, bulu tangkis juga harus dimainkan dengan teknik-teknik tertentu. Pemain bulu tangkis harus menguasai sejumlah teknik dasar, mulai dari cara memegang raket hingga melakukan pukulan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Cara Memegang Raket', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik forehand', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini sama seperti ketika Anda memegang benda pada umumnya. Tangan harus menggenggam pegangan raket, sedangkan telunjuk & ibu jari membentuk sudut atau huruf V.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik backhand', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Hampir sama seperti teknik forehand, hanya saja posisi ibu jari tidak bertemu dengan ujung jari lainnya, melainkan disejajarkan dengan pegangan raket sehingga mendekati telunjuk.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('2. Posisi Badan atau Sikap Berdiri (stance)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Sikap berdiri dalam bulu tangkis:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Badan bertumpu pada kedua kaki,', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Kedua kaki dibuka selebar bahu dan agak ditekuk. Bisa juga salah satu kaki ke depan dan yang lainnya sedikit ke belakang, dan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Tangan agak diangkat dan ditekuk sehingga raket sejajar dengan dada atau kepala.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('3. Kerja Kaki (footwork)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Bulu tangkis menuntut para pemainnya untuk bergerak lincah dan cepat, karena itu kerja kaki atau footwork punya peran yang sangat penting di dalam permainan. Kaki tidak hanya untuk memposisikan badan, tetapi juga jadi tumpuan sekaligus pusat keseimbangan tubuh.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('4. Servis Bulutangkis', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Servis artinya memukul kok untuk memulai permainan. Kok yang dipukul harus mengarah pada area lawan dan melewati net. Teknik servis sendiri ada tiga macam, yaitu sebagai berikut.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Forehand Pendek -> Pemain memukul kok dengan tidak begitu kuat. Akibatnya, kok meluncur dan akan jatuh di sekitar net atau di area depan tim lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Forehand Tinggi -> Teknik ini dilakukan untuk membuat kok melambung tinggi dan jatuhnya cukup jauh dari area net. Teknik ini bertujuan agar kok bisa jatuh di belakang pemain lawan sehingga mereka kesulitan untuk mengembalikannya.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Backhand -> Servis backhand dilakukan dengan tenaga sedang. Tujuannya agar kok bisa jatuh di dekat garis serang lawan dan mendarat setelah sedikit melewati net. Hal ini juga bertujuan agar lawan kesulitan mengembalikan serangan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('5. Cara Memukul', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik memukul dan mengembalikan serangan kok bisa bermacam-macam. Setiap tekniknya juga bisa menjadi penentu kemenangan tim. Setidaknya, ada lima jenis yang patut Anda ketahui, yaitu pukulan lob, drop shot, drive, netting, dan smash.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('a. Lob', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini dilakukan dengan cara memukul kok agar bisa terbang setinggi mungkin dan jatuhnya di belakang garis lapangan area tim lawan. Pukulan seperti ini biasanya akan membuat lawan kewalahan sehingga mereka pun jadi cepat lelah.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('b. Drop shot', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Pukulan drop shot bertujuan untuk mematikan pergerakan lawan. Pukulannya dilakukan secara lurus dan menggunakan tenaga kecil atau pelan, tujuannya agar kok bisa jatuh di sekitar net.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini sering digunakan untuk mengecoh lawan. Pemain biasanya akan melompat dan berpura-pura hendak smash sehingga tim lawan pun bersiap-siap di area belakang. Akan tetapi, pukulan yang dilakukan ternyata adalah drop shot dan kok justru jatuh di dekat net.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('c. Drive', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Drive adalah jenis pukulan yang mendatar. Arah pukulannya bisa lurus atau menyilang untuk menyasar sisi samping tim lawan. Teknik ini biasanya dilakukan untuk menyerang maupun mengembalikan serangan dengan cepat', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('d. Netting', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Sesuai namanya, ini adalah jenis pukulan yang bertujuan agar kok jatuh tepat di net setelah berhasil melewatinya. Pukulan netting ini cukup sulit dilakukan karena butuh akurasi tinggi. Bila berhasil, tim lawan akan kesulitan mengembalikan serangan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('e. Smash', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Smash adalah jenis pukulan yang bertujuan untuk menyerang sekaligus mematikan gerakan lawan. Pukulannya sendiri sangat keras dan menukik ke bawah. Untuk melakukan smash, pemain harus memukul kok dengan sekuat tenaga.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        Text('Tujuannya agar kok bisa melaju cepat dan lawan tidak sempat untuk mengembalikan serangan. Smash juga biasanya dilakukan dengan cara melompat untuk menghasilkan serangan yang cepat, kuat, dan arahnya menukik tajam ke bawah lapangan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify,),
                        SizedBox(height: 50.0,),
                        Container(
                          width: MediaQuery.of(context).size.width,
                          height: 55,
                          child: RaisedButton(
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10.0),
                                side: BorderSide(color: Colors.pink)),
                            onPressed: () {
                              Navigator.of(context).push(
                                MaterialPageRoute(
                                  builder: (context){
                                    return Home();
                                  },
                                ),
                              );
                            }, color: Colors.pink,
                            textColor: Colors.white,
                            child: Text(
                              'Kembali',
                              style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.left, ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
