import 'package:edukaquiz_app/home.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Basket extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: double.infinity,
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Column(
            children: <Widget>[
              SizedBox(height: 70,),
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Image.asset('assets/gambarbasket.png' , width: 370.0,),
              ),
              SizedBox(height: 40,),
              SingleChildScrollView(
                child: Container(
                  width: 450,
                  decoration: BoxDecoration(
                    color: Color(0xff59E0FE),
                    borderRadius: BorderRadius.only(topLeft: Radius.circular(60), topRight: Radius.circular(60),
                    ),
                  ),
                  child: Container(
                    margin: EdgeInsets.all(25),

                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        SizedBox(height: 10,),
                        Align(
                          alignment: Alignment.centerLeft,
                          child: Text(
                            'Basket',
                            style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('Pengertian Permainan Bola Basket',style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),textAlign: TextAlign.justify, ),
                        SizedBox(height: 8,),
                        Text('Permainan bola basket adalah salah satu cabang olahraga yang dimainkan oleh dua tim yang mana setiap tim berisi lima orang pemain. Cara bermain bola basket pun bisa dibilang cukup mudah, yaitu dengan mencari point sebanyak mungkin dengan cara memasukkan bola ke ring (keranjang) lawan.',style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal),textAlign: TextAlign.justify, ),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Memegang Bola Basket ', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        Text(' Basket ', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Berikut teknik dasar memegang bola basket yang baik dan benar:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Gunakan kedua tangan untuk memegang basket', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('2. Asumsikan ketika memegang bola seakan-akan memegang mangkok besar, sehingga ruas-ruas jari dan telapak tangan terbuka lebar serta melekat pada bola', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('3. Posisikan kedua telapak tangan samping di kanan dan kiri (berada agak ke belakang bola)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('4. Buka lebar kedua kaki dengan posisi salah satu kaki berada agak ke depan (dibuat senyaman mungkin)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('5. Condongkan badan sedikit ke depan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('6. Buat posisi badan serileks mungkin saat memegang bola', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Passing', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Dalam gerakan passing terdapat beberapa teknik yang bisa digunakan dan dikuasai untuk meningkatkan skill pemain, beberapa diantaranya :', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Teknik Chess Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dari posisi setinggi dada. Gunakan lemparan dua tangan untuk menghasilkan lemparan yang lurus dan terarah.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('2. Teknik Overhead Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dari posisi di atas kepala. Tujuan dari gerakan ini yaitu untuk melakukan counter attack yang mana hasil lemparan bola bisa melambung jauh ke arah area lawan. Selain itu teknik ini juga bisa digunakan saat kita ingin membebaskan diri dari kawalan ketat lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('3. Teknik Bounce Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dengan cara memantulkan bola ke lantai menuju kawan. Tujuan teknik ini yaitu untuk bisa menghindari hadangan lawan serta bisa mengumpan ke arah kawan dengan akurat.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('4. Teknik Baseball Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dengan posisi bola berada di atas atau di belakang kepala. Untuk melakukan gerakan ini, diperlukan satu tangan yang kuat agar hasil lemparan maksimal. Selain itu, teknik ini bisa digunakan untuk mengelabuhi lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('5. Teknik Behind Back Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dari belakang badan yang dipantulkan ke lantai menuju kawan. Gerakan ini hampir mirip dengan gerakan bounce pass.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('6. Teknik Hook Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini merupakan gerakan melempar bola dengan menggunakan satu tangan yang mana lengan tangan seakan berbentuk kail pancing. Untuk menghasilkan lemparan umpan yang lebih tinggi, posisi bola bisa diletakkan lebih jauh ke arah pundak kita.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('7. Teknik Under Pass', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Pada teknik umpan ini, bisa dilakukan dari bawah atau bola berada sekitar pinggang dan mengarahkannya lurus pada kawan satu tim yang akan di beri umpan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Catching', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik catching adalah salah satu materi bola basket yang mana gerakannya ditujukan untuk menerima bola baik dari tim kawan, maupun bola yang datang dari tim lawan. Berikut ini cara melakukannya.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Fokus ke datangnya bola', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('2. Tangkap bola dengan telapak tangan yang terbuka lebar sembari melebarkan jari-jari tangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('3. Ketika bola sudah berada di tangan, genggam bola dengan jari-jari tangan yang telah direntangkan selebar mungkin yang diikuti dengan gerakan menarik bola', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Menggiring Bola Basket (Dribbling)', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Dribbling adalah gerakan menggiring dalam basket dengan cara memantul-mantulkan bola ke lantai. Saat memantulkan bola ke lantai, pemain bisa menggunakan satu atau dua tangan secara bergantian. Gerakan ini dapat dilakukan dengan cara berlari maupun berjalan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ada satu hal penting yang harus diperhatikan ketika melakukan teknik dribbling, yaitu sebisa mungkin pemain harus bisa mengontrol bola sebaik mungkin agar bola tidak dicuri oleh lawan. Materi bola basket dribble dibagi menjadi 6 bagian, yaitu sebagai berikut.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dribbling Bola Tinggi', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini mengharuskan pemain untuk melakukan gerakan dribbling dengan kecepatan tinggi. Gerakan ini biasanya digunakan pada saat masuk area pertahanan lawan dengan cara berlari maupun berjalan cepat', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dribbling Bola Rendah', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini biasanya digunakan saat berhadapan langsung dengan lawan untuk mempertahankan bola ketika lawan hendak merebutnya. Dengan menguasai teknik ini, maka akan mempermudah kita mempertahankan bola.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Spin Dribble', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Gerakan pada teknik ini tergolong susah, lho. Hal ini karena pemain harus melakukan gerakan spin, sehingga diperlukan latihan teratur agar gerakan dribble bisa stabil dan bola menjadi lebih mudah untuk dikendalikan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Between the Legs Dribble', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Gerakan ini memprioritaskan pada proses dribbling bola dimana posisi bola ditempatkan di depan kaki. Teknik ini juga termasuk teknik yang cukup sulit bagi pemula, butuh latihan konsisten untuk menguasainya.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Behind the Back Dribble', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Fokus utama dari teknik ini ialah penempatan bola di belakang pemain agar bola menjadi susah untuk direbut oleh lawan. Butuh skill khusus untuk menguasai gerakan ini.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Crossover Dribble', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        Text('Gerakan ini berfokus pada posisi menyilang yang dilakukan pemain. Gerakan ini bertujuan untuk mengecoh lawan agar susah menebak gerakan kita.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Pivot', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Materi bola basket selanjutnya yaitu gerakan pivot. Teknik ini merupakan gerakan memutar dengan menggunakan satu kaki, sementara kaki lainnya berperan sebagai poros. Gerakan pivot bertujuan untuk menyelamatkan bola dari jangkauan lawan yang hendak merebut.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Hal terpenting untuk menguasai teknik ini yaitu kaki yang menumpu tidak boleh bergeser saat memutar badan, dan ini sudah aturannya. Biasanya pivot dibarengi dengan gerakan passing, dribbling serta shooting.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Shooting', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Shooting merupakan salah satu gerakan inti pada olahraga bola basket. Gerakan ini bertujuan untuk mengarahkan bola langsung menuju ring lawan serta mencetak poin bagi tim. Untuk melakukan shooting bisa menggunakan satu atau dua tangan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ada beberapa gerakan shooting yang bisa dilakukan saat permainan basket, mulai dari set shoot, jump shoot, lay-up shoot, hingga slam dunk.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Set Shoot', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini dilakukan dengan cara tanpa melompat sembari melemparkan bola menuju ring lawan. Gerakan ini bisa dibilang jarang dilakukan oleh pemain basket pada umumnya. Ini terjadi karena ketika melakukan shooting tanpa melakukan lompatan, maka bola akan dengan mudah dihalangi oleh lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Biasanya tembakan jenis ini dilakukan pada saat lemparan bebas atau biasa disebut dengan free throw.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Jump Shoot', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Gerakan shooting ini dilakukan dengan cara melompat. Teknik shooting yang satu ini sering dilakukan saat pemain ingin melakukan tembakan, akan tetapi kesulitan mendekati ring lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Dikarenakan pada jenis tembakan ini pemain bisa melakukan shoot pada titik tertinggi yang menyebabkan tim musuh kuwalahan menghadang tembakan, maka bisa dikatakan teknik ini memiliki persentase keberhasilan yang cukup besar dalam mencetak angka.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Lay-up Shoot', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik ini dilakukan setelah menggiring bola hingga mendekati ring lawan, lalu ketika ring sudah dalam jangkauan, pemain bisa melakukan shoot dengan melompat ke arah atas sembari mengangkat tangan untuk memasukkan bola ke ring.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Slam Dunk', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        Text('Untuk melakukan gerakan ini, pemain harus melakukan lompatan yang tinggi sebelum melakukan shoot bola ke arah ring langsung. Kombinasi antara lompatan yang tinggi dengan postur tubuh yang besar, akan mempersulit lawan dalam menghentikan gerakan slam dunk kita serta membuat persentase keberhasilan mencetak angkanya semakin besar juga.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Screen', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Dalam olahraga bola basket, terdiri dari beberapa pemain yang memiliki tugasnya masing-masing. Teknik screen sendiri merupakan teknik yang dilakukan oleh pemain yang memiliki tugas sebagai penyerang.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Tujuan utama gerakan ini yaitu untuk menutup pergerakan dari tim lawan yang melakukan penjagaan pada tim kita, kemudian membuka jalan untuk kawan satu tim agar bisa melewati belakang pemain lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Teknik Dasar Rebound', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Teknik rebound merupakan teknik dasar yang sangat penting dalam permainan bola basket. Pada teknik ini, gerakannya berfokus untuk merebut bola yang hampir masuk ke dalam ring. Umumnya teknik ini dibagi menjadi dua, yaitu rebound defensif dan rebound ofensif.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Rebound defensif adalah gerakan merebut bola dari lawan yang hendak memasukkan bola ke ring kita namun gagal. Sedangkan rebound ofensif merupakan lemparan yang dilakukan oleh kawan satu tim, namun gagal masuk ke ring dan direbut kembali oleh teman setim kita untuk dimasukkan lagi ke dalam ring lawan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Kedua teknik rebound ini bisa dibilang cukup krusial dan penting untuk dikuasai pemain basket. Dengan menguasai teknik ini, pemain mampu memberikan tim posession ball yang baik hingga bisa memenangkan pertandingan.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Peraturan Permainan Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Berikut ini peraturan permainan bola basket secara umum:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Setiap pertandingan basket terdiri dari dua tim yang bertanding', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Tiap tim maksimal terdiri dari 12 pemain, dan 5 pemain sebagai pemain inti di lapangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Masing-masing tim diperbolehkan melakukan pergantian pemain tanpa batas', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Pemain diperbolehkan melempar bola dengan menggunakan satu atau kedua tangan ke segala arah', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Pemain diperbolehkan memukul bola dengan satu atau kedua tangan ke segala arah, akan tetapi tidak diizinkan memukul dengan tinjuan atau kepalan tangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Bola basket wajib dimainkan menggunakan tangan, selain tangan (lengan ataupun kaki) tidak diperbolehkan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Pemain dilarang mendorong, memukul, menanduk, menyeruduk, menahan bola dalam waktu yang cukup lama, serta menjegal lawan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Poin angka akan didapatkan lawan jika salah satu dari tim kawan melakukan kesalahan tiga kali berurutan tanpa adanya pelanggaran dari tim lawan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Poin angka akan didapatkan apabila pemain berhasil melakukan lemparan dari lapangan dan masuk ke dalam ring', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Jika bola keluar lapangan, maka bola akan dilemparkan kembali ke dalam. Pemain yang pertama kali menyentuhnya berhak mendapatkan bola dan memainkannya', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Tim yang mencetak gol atau mendapatkan angka terbanyak, berhak memenangkan pertandingan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Pemain yang menguasai bola dan posisinya berada di garis paling depan, dilarang mengumpan bola kebelakang hingga melewati garis tengan, hal ini berlaku juga untuk lemparan dari luar ruangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Peraturan Waktu Permainan Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Seperti halnya cabang olah raga lainnya, permainan bola basket juga memiliki batasan waktu. Permainan ini terdiri dari dua babak dimana setiap babak berdurasi 20 menit, dengan waktu istirahat setelah babak pertama selama 10 menit.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Organisasi nasional maupun lokal memperbolehkan memperpanjang waktu permainan dari 2 babak menjadi 4 babak, yang mana masing-masing babak batas waktunya selama 10 menit.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Khusus permainan bola basket mini, aturan yang berlaku yaitu dalam pertandingan terdiri dari 4 babak yang mana setiap babak pertandingan berlangsung selama 10 menit dan 2 menit untuk waktu istirahat. Dalam dunia basket, terdapat aturan waktu yang berlaku:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Aturan 3 detik, yaitu dimana pemain yang teman satu timnya menguasai bola, dilarang berdiri di area bersyarat dengan durasi lebih dari 3 detik', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Aturan 5 detik, yaitu saat terjadi lemparan ke dalam dan bola berhasil diambil, pemain memiliki batas waktu selama 5 detik untuk mengumpan bola ke pemain lain', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Aturan 10 detik, yaitu dimana dalam satu tim tidak boleh memainkan bola dalam durasi lebih dari 10 detik di dalam areanya sendiri', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Aturan 30 detik, yaitu tim yang memegang bola pada saat pertandingan, memiliki waktu 30 detik sebelum batas waktu tembakan ke ring habis', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Wasit Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Tidak hanya pertandingan sepak bola, dalam pertandingan basket juga memiliki wasit yang memandu jalannya pertandinganWasit permainan bola basket:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Tiga wasit, yaitu wasit yang bertanggung jawab dalam memimpin jalannya pertandingan serta memastikan para pemain patuh terhadap aturan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('2. Pencatat waktu, yaitu yang bertanggung jawab dalam waktu permainan dan waktu diskon dalam permainan basket', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('3. Penanda waktu dan pembantu, yaitu wasit yang bertugas dalam pengisian buletin permainan dengan jumlah absen tim (tiap pemain), untuk mendaftarkan poin yang ditandai, dan lainnya', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('4. Operator 30 detik, yaitu yang bertanggung jawab atas waktu serangan dari kedua tim, karena setiap tim memiliki waktu hanya 30 detik untuk melakukan serangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Hak dan tugas wasit basket:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('1. Memperhatikan dengan seksama permainan yang dimainkan oleh kedua tim yang bertanding', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('2. Mencatat semua pelanggaran yang dilakukan pemain', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('3. Melaporkan ke wasit pembantu apabila terjadi pelanggaran berturut-turut', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('4. Berhak men-diskualifikasi pemain yang melakukan pelanggaran tertentu', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('5. Memperhatikan pergerakan bola', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('6. Berhak mengambil keputusan baik ketika pergantian kepemilikan bola atau saat bola telah dianggap keluar lapangan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('7. Menghitung waktu serta banyaknya gol yang berhasil didapatkan', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Ukuran Lapangan Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Dalam permainan bola basket, lapangan yang digunakan harus memiliki standar ukuran tertentu. Bagi kalian yang sedang mencari ukuran lapangan bola basket, bisa disimak info berikut ini.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Ukuran dan Gambar Lapangan Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Materi bola basket selanjutnya yaitu tentang ukuran lapangan basket. Lapangan basket mempunyai bentuk persegi panjang yang mana menurut standar dari National Basketball Asociation memiliki panjang lapangan 28,5 meter serta lebarnya 15 meter. Ukuran ini sedikit berbeda dengan standar Federasi Bola Basket Internasional, yaitu panjang lapangan 26 meter dan lebarnya 14 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Jumlah lingkaran pada lapangan bola basket yaitu tiga buah, yang mana setiap lingkaran berdiameter 3,6 meter. Panjang garis tengahnya yaitu 1,8 meter dengan lebar garisnya selebar 0,05 meter. Untuk panjang garis akhir lingkaran pada daerah serang sepanjang 6 meter, sedangkan ukuran pajang garis tembakan (hukuman) berukuran 3,6 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ukuran jarak papan pantul bagian bawah dengan lantai lapangan yaitu sebesar 2,75 meter, sedangkan jarak ring dengan papan pantul bagian bawah sebesar 0,30 meter. Ring basket sendiri memiliki ukuran panjang 0,40 meter dan jaran antar tiang penyangganya dengan garis akhir sebesar 1 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Untuk ukuran papan pantul pada bagian luar yakni sebesar 1,80 meter dengan lebar 1,20 meter. Sedangkan ukuran panjang papan pantul bagian dalam sebesar 0,59 meter dengan lebar sebesar 0,45 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 8,),
                        Text('Ukuran Lapangan Bola Basket', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Ukuran standar lapangan bola basket Internasional (FIBA):', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Panjang lapangan baket memiliki ukuran sebesar 28 meter (92 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Lebar lapangan basket memiliki ukuran sebesar 15 meter (49 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Tinggi ring bola basket sebesar 3,05 meter (10 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Ukuran radius dibatasi busur sebesar 1,25 meter (4,10 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Lingkaran pada pusat lapangan basket diameternya sebesar 3,66 meter (11,81 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Garis lemparan bebas bola, jarak dari titik pada lantai langsung langsung ke bawah backboard memiliki ukuran sebesar 4,6 meter (15,09 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Ukuran jarak 3 points garis dari ring memiliki ukuran 6,75 meter 6,60 meter in corner', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text(' Ukuran standar lapangan bola basket nasional (PERBASI):', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('- Panjang lapangan basket memiliki ukuran sebesar 29 meter (94 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Lebar lapangan basket memiliki ukuran sebesar 15 meter (50 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Ketinggian ring basket 3,05 meter (10 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Ukuran radius dibatasi busur sebesar 1,22 meter (4 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Lingkaran pada pusat lapangan basket diameternya sebesar 3,66 meter (11,81 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Garis lemparan bebas bola, jarak dari titik pada lantai langsung langsung ke bawah backboard memiliki ukuran sebesar 4,57 meter (15 ft)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('- Ukuran jarak 3 points garis dari ring memiliki ukuran 7,27 meter 6,70 meter in corner', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 5,),
                        Text('Untuk jarak bangku pemain basket cadangan dan mengawas pertandingan, jaraknya minimal 2 meter. Ini dilakukan untuk memberi tempat kosong saat run off. Sedangkan jarak bangku penonton ke garis tepi lapangan basket yaitu minimal 5 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ukuran standar atap stadion lapangan basket internasional yaitu 9,1 meter dari lantai lapangan. Lapangan basket harus memiliki clearance minimal 7,7 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ukuran standar atap stadion lapangan basket internasional yaitu 9,1 meter dari lantai lapangan. Lapangan basket harus memiliki clearance minimal 7,7 meter.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Papan pantul ini terbuat dari bahan yang keras yang diletakkan dibelakang ring untuk menghasilkan pantulan bola yang bagus. Selain itu papan pantul ini juga digunakan untuk mempermudah pemain untuk memasukkan bola ke ring dengan teknik pantulan bola.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ukuran standar papan pantul bola basket:', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Bagian luar papan pantul memiliki ukuran panjang dan lebar masing-masing sebesar 1,8 meter dan 1,05 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Bagian dalam papan pantul memiliki ukuran panjang dan lebar masing-masing sebesar 0,59 meter dan 0,45 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('ukuran Jarak antara papan pantul dengan lantai lapangan yaitu sebesar 2,75 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Jarak antara ring basket ke bagian bawah papan pantul sebesar 0,15 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('ukuran jarak antara tiang penyangga hingga ke garis akhir yaitu sebesar 1 meter', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ukuran Keranjang Bola Basket (Ring)', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        Text('Ring dalam permainan bola basket berbentuk jala yang bagian bawahnya terdapat lubang yang berfungsi agar bola bisa keluar setelah masuk ke dalam ring. Bahan dasar dari ring ini yaitu besi yang keras dan kuat, sedangkan jalanya (keranjang) terbuat dari anyaman tali dari bahan nilon.', style: TextStyle(fontSize: 15, fontWeight: FontWeight.normal, ), textAlign: TextAlign.justify,),
                        SizedBox(height: 50.0,),
                        Container(
                          width: MediaQuery.of(context).size.width,
                          height: 55,
                          child: RaisedButton(
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10.0),
                                side: BorderSide(color: Colors.pink)),
                            onPressed: () {
                              Navigator.of(context).push(
                                MaterialPageRoute(
                                  builder: (context){
                                    return Home();

                                  },
                                ),
                              );
                            }, color: Colors.pink,
                            textColor: Colors.white,
                            child: Text(
                              'Kembali',
                              style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),textAlign: TextAlign.left, ),
                          ),
                        ),

                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
